include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "android/build/**"
    - "build/**"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks