name: pora
description: "PORA"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.12.2
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  intl: ^0.20.2
  auto_route: ^11.1.0
  get_it: ^9.2.1
  flutter_dotenv: ^6.0.1
  talker_flutter: ^5.1.17
  talker_dio_logger: ^5.1.19
  pinput: ^6.0.2
  equatable: ^2.0.8
  phosphoricons_flutter: ^1.0.0
  retrofit: ^4.9.2
  dio: ^5.10.0
  json_annotation: ^4.12.0
  flutter_secure_storage: ^10.3.1
  flutter_gen: ^5.14.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.3
  pretty_qr_code: ^3.6.0
  share_plus: ^13.2.0
  flutter_slidable: ^4.0.3
  image_cropper: ^12.2.1
  flutter_image_compress: ^2.4.0
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.0.1
  http: ^1.2.0
  html: ^0.15.4
  web_socket_channel: ^3.0.3
  connectivity_plus: ^6.1.0
  liquid_glass_easy: ^3.3.1
  path_provider: any
  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  auto_route_generator: ^10.5.0
  mobx_codegen: ^2.7.7
  change_app_package_name: ^1.5.0
  json_serializable: ^6.14.0
  retrofit_generator: ^10.2.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/app_logo.png

  fonts:
      - family: Inter
        fonts:
              - asset: assets/fonts/Inter_18pt-Regular.ttf
              - asset: assets/fonts/Inter_18pt-Medium.ttf
                weight: 500
              - asset: assets/fonts/Inter_18pt-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Inter_18pt-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
                weight: 800
